@url=http://localhost:3000

### Cria um novo link
POST {{url}}/links
Content-Type: application/json

{
  "legenda": "Pesquisa Google",
  "urlOriginal": "https://www.google.com"
}

### Buscar todos os links (se existir esse endpoint)
GET {{url}}/links

### Buscar um link específico pelo código (exemplo)
GET {{url}}/links/34VoZW
